spring:
  datasource:
    url: jdbc:h2:mem:assignment
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    open-in-view: false
  sql:
    init:
      mode: always

jwt:
  key: FB75864A-D868-11ED-A422-0A146EBA9A4E